### ISSUE TITLE
Config class needed functions

### ISSUE THREAD

**Issue by Pommfritz0308** [wrottger/webserv#15]
Path example: /hund/bellen.py

- getBestMatchingLoacationBlock(string -> Path)
- isMethodAllowed(string -> Path, string -> Method)
- isCgiAllowed(string -> Path, string -> Fileextension)
- getRootDirectory(string -> Path)

=> Search only if no exact route found in config file
=> Search through location blocks for the closest level path that matches the unmatched request route
=> If requested route is not found in root then respond with bad request

![image](https://github.com/wrottger/webserv/assets/120736394/20b91ac7-025c-48a0-8257-cb1a55ab20a9)

**Comment by Pommfritz0308** [comment]
check latest commit on my config branch

**Comment by stevebalk** [comment]
![image](https://github.com/wrottger/webserv/assets/118443457/bac25b4a-6350-4f56-93fa-3e7b7e4052ef)

**Comment by stevebalk** [comment]
**getFilePath(string -> Path)**
Should return the complete filepath, like: 
/var/www/server1/cgi-bin/script.py
/var/www/server2/index.html

**getDirPath(string -> Path)**
Should return the path without the file, like:
/var/www/server1/cgi-bin/
/var/www/server2/
