### ISSUE TITLE
Encapsulate config parsing

### ISSUE THREAD

**Issue by stevebalk** [wrottger/webserv#9]
At the moment every data-structure like TokenType, LocationBlock etc. and error.hpp are accessible outside there scope.
It would be good if they where only accessible inside their used scope.

**Comment by Pommfritz0308** [comment]
But they are not accessible outside their scope since they're not declared globally. You would have to include the respective header to use them.

**Comment by stevebalk** [comment]
![image](https://github.com/wrottger/webserv/assets/118443457/5cf73213-b965-4cf1-87c6-5ff90cb34557)

**Comment by StrongCoding** [comment]
[rainbow]rocket[/rainbow]

**Comment by Pommfritz0308** [comment]
![nc8vhrqcr6rb1](https://github.com/wrottger/webserv/assets/120736394/5576b3fb-22ef-4025-af24-8ab1ce2ecab0)

**Comment by StrongCoding** [comment]
fixed with https://github.com/wrottger/webserv/pull/13

**Comment by jnspr** [comment]
find ich auch :^)

**Comment by stevebalk** [comment]
![image](https://github.com/wrottger/webserv/assets/118443457/8d49687e-cc66-45ec-bf2f-fb00d87b2013)
